### PR TITLE
Added logic for BIN Identification

### PR DESCRIPTION
**Pull request by rai-rakesh**
* Logic is just to identify BIN and add image accordingly , we can further add to disable buttons on basis on validity.

### CODE REVIEW

**Comment by mkagenius** [comment]
@rai-rakesh Thanks for the PR. Will it be possible to use smaller image sizes, they are currently 10KB each. We can do with 1KB also as they will be displayed in smaller sizes eventually.

**Comment by rai-rakesh** [comment]
> @rai-rakesh Thanks for the PR. Will it be possible to use smaller image sizes, they are currently 10KB each. We can do with 1KB also as they will be displayed in smaller sizes eventually.

done. 😃

**Comment by mkagenius** [comment]
image
The icon does show up in dark mode but somehow not visible in normal mode? 

I tested this using.
```
(base) ~/Work/cc-billpay-upi-id$ npm run dev
```

**Comment by mkagenius** [comment]
@rai-rakesh Nevermind, it worked on the second try on light theme as well
image

**Pull request merged**
