### PR TITLE
small QR generate and overlay on click.

### PR DESCRIPTION
**Pull request by preetmungara**
Added amount section(optional), small QR generate and on click on QR, it opens up as overlay. 

image
image

### CODE REVIEW

**Comment by mkagenius** [comment]
Looks nice, let me test it locally. Do we need the amount option? It adds a hinderance that they will need to check what exactly their bill is (atleast it gives that perception). They can enter the amount in the app is what i feel.

**Comment by mkagenius** [comment]
@preetmungara lets just push the QR code for now. We can discuss the amount field and decide on it, later on. That way QR code will be available to users asap. You can send a new pull request.

**Comment by preetmungara** [comment]
@mkagenius Amount field is optional currently, even if user don't add the amount, it would generate the QR code. do you think we need to remove it?

**Comment by mkagenius** [comment]
We can remove the input field for now. It needs a little more thought. We
can create another issue and discuss that.

**Comment by preetmungara** [comment]
@mkagenius Done.

**Review by mkagenius — APPROVED** [review]

**Comment by mkagenius** [comment]
Merged, the tool is live with QR code. Also posted an update on the subreddit. Great job!

**Pull request merged**
